version: "3"

services:
  mbed-sim:
    image: ghcr.io/djgoldsmith/mbed-simulator:release
    build:
      context: .
    ports:
      - "7829:7829"
    volumes:
      - "./server:/app/server"
      - "./viewer:/app/viewer"
